plugins:
  debtcollective_wizards_enabled:
    client: false
    default: true
  debtcollective_solidarity_message_author:
    default: "system"
    client: false
  debtcollective_solidarity_message_title:
    default: "Solidarity Bloc"
    client: false
